### ISSUE TITLE
Error handling on user mutations?

### ISSUE THREAD

**Issue by ryanjones** [zauberware/rails-devise-graphql#15]
I've started to play around with this project a bit more and I'm curious if there would be appetite to have error handling added into the user mutations? For example, the SignUp mutation doesn't handle a lot of the common signup errors (account exists, invalid pw length, etc.)

Not sure how far you want this project to go in terms of boiler plate. I'm already adding the common error handling scenarios to a small hobby project I'm working on, so I would just flip them back into this repo. Let me know and I can start contributing back (similar to #7).

**Comment by simonfranzen** [comment]
Hey @ryanjones thanks for your request. I should really update the boilerplate. We have also added some more functionality in an internal project I would like to add here.

Please go ahead with your PR. I would join the next weeks and update my stuff as well.

**Comment by simonfranzen** [comment]
hey @ryanjones, we have switched to graphql-auth gem to provide authentication. I did a fork to support rails6 and this is hopefully merged soon.
