### ISSUE TITLE
Devise confirmable

### ISSUE THREAD

**Issue by kockok** [zauberware/rails-devise-graphql#8]
Please add devise confirmable to graphql implementation.

**Comment by simonfranzen** [comment]
Good point!

**Comment by kockok** [comment]
Just wondering why emails are disabled...

**Comment by simonfranzen** [comment]
For no reason @kockok .
We have to set this line to true https://github.com/zauberware/rails-devise-graphql/blob/ed3e1cca2b6eafb011960de02f133c8d789e021c/config/environments/production.rb#L62

If you want, just make a PR

**Comment by simonfranzen** [comment]
We use graphql-auth now for authentication handling so I close this issue.

**Comment by simonfranzen** [comment]
@kockok I also enabled mails for production
